[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "php artisan migrate --force --path=database/migrations/2026_09_24_092101_create_promotional_popups_table.php --path=database/migrations/2026_09_24_100549_create_demo_orders_table.php --path=database/migrations/2026_09_24_111035_add_login_ip_and_ip_bans.php"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
