import { useState } from 'react';
import { Search, X, CheckCircle2, MessageSquare, Flag } from 'lucide-react';
import { apiRequest } from '../../context/AuthContext';

type SupportTicket = { id: number; name: string; email: string; order_number: string | null; subject: string; message: string; status: string; priority: string; admin_note: string | null; admin_reply: string | null; created_at: string; responded_at: string | null };

export function AdminSupportInbox({ tickets, onRefresh }: { tickets: Record<string, unknown>[]; onRefresh: () => Promise<void> }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [priority, setPriority] = useState('all');
  const [selected, setSelected] = useState<SupportTicket | null>(null);
  const filtered = (tickets as SupportTicket[]).filter(ticket => {
    const matchesQuery = `${ticket.name} ${ticket.email} ${ticket.order_number || ''} ${ticket.subject}`.toLowerCase().includes(query.toLowerCase().trim());
    return matchesQuery && (status === 'all' || ticket.status === status) && (priority === 'all' || ticket.priority === priority);
  });

  return <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Support inbox</h2><p>Review customer requests, reply, and resolve tickets.</p></div><span>{filtered.length} of {tickets.length} requests</span></div><div className="admin-support-filters"><label><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name, email, order..." /></label><select value={status} onChange={event => setStatus(event.target.value)} aria-label="Filter support status"><option value="all">All statuses</option><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><select value={priority} onChange={event => setPriority(event.target.value)} aria-label="Filter support priority"><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="normal">Normal</option><option value="low">Low</option></select></div>{filtered.length ? <div className="admin-table-scroll"><table><thead><tr><th>Customer</th><th>Subject</th><th>Priority</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{filtered.map(ticket => <tr key={ticket.id}><td><strong>{ticket.name}</strong><span className="admin-table-subtext">{ticket.email}</span></td><td>{ticket.subject}{ticket.order_number && <span className="admin-table-subtext">Order: {ticket.order_number}</span>}</td><td><span className={`admin-support-priority ${ticket.priority}`}>{ticket.priority}</span></td><td><span className={`admin-support-status ${ticket.status}`}>{ticket.status}</span></td><td>{new Date(ticket.created_at).toLocaleDateString()}</td><td><button type="button" className="admin-text-link" onClick={() => setSelected(ticket)}>Open <MessageSquare size={14} /></button></td></tr>)}</tbody></table></div> : <p className="admin-empty">No support requests match your filters.</p>}{selected && <SupportTicketEditor ticket={selected} onClose={() => setSelected(null)} onSaved={async () => { setSelected(null); await onRefresh(); }} />}</section>;
}

function SupportTicketEditor({ ticket, onClose, onSaved }: { ticket: SupportTicket; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState({ status: ticket.status, priority: ticket.priority, admin_note: ticket.admin_note || '', admin_reply: ticket.admin_reply || '' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const update = (field: string, value: string) => setForm(current => ({ ...current, [field]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await apiRequest(`/api/admin/support/${ticket.id}`, { method: 'PUT', body: JSON.stringify(form) }); await onSaved(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not update ticket.'); setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-2xl rounded-2xl border border-brand-cardBorder bg-brand-card p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gold">Support ticket #{ticket.id}</p><h2 className="mt-1 text-xl font-bold text-white">{ticket.subject}</h2><p className="mt-1 text-xs text-gray-400">{ticket.name} · {ticket.email}</p></div><button type="button" onClick={onClose} aria-label="Close ticket" className="text-gray-400 hover:text-white"><X size={18} /></button></div><div className="admin-ticket-message"><p>{ticket.message}</p>{ticket.order_number && <span>Order: {ticket.order_number}</span>}</div><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-gray-300">Status<select value={form.status} onChange={event => update('status', event.target.value)} className="admin-modal-input"><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label><label className="text-xs font-bold text-gray-300">Priority<select value={form.priority} onChange={event => update('priority', event.target.value)} className="admin-modal-input"><option value="urgent">Urgent</option><option value="normal">Normal</option><option value="low">Low</option></select></label></div><label className="block text-xs font-bold text-gray-300">Internal note<textarea rows={3} value={form.admin_note} onChange={event => update('admin_note', event.target.value)} className="admin-modal-input" placeholder="Visible only to admins" /></label><label className="block text-xs font-bold text-gray-300">Reply to customer<textarea rows={4} value={form.admin_reply} onChange={event => update('admin_reply', event.target.value)} className="admin-modal-input" placeholder="Write a response for this customer" /></label>{error && <p role="alert" className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-300">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-brand-cardBorder px-4 py-2 text-xs font-bold text-gray-400">Cancel</button><button disabled={saving} className="account-gold-button">{saving ? 'Saving...' : 'Save ticket'}</button></div></form></div></div>;
}
